language: node_js
node_js:
  - "6"
  - "7"
cache:
   directories:
     - node_modules
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install
script:
  - npm run build
  - npm test:ci